spring:
 datasource:
  url: jdbc:mysql://localhost:3306/cloudvendor?mysql-connector allowPublicKeyRetrieval=true&useSSL=false
  username: root
  password: root

#JPA Setting
 jpa.hibernate.ddl_auto: create